//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18408
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
public static class Device
{
	public static int Width = Display.main.systemWidth;
	public static int Height = Display.main.systemHeight;
	public static float MultiX = Display.main.systemWidth / 480;
	public static float MultiY = Display.main.systemHeight / 800;
	
}		

